name: data_validator
description: This lib implements a data validator for generic data objects.
version: 1.0.0
repository: https://github.com/ArturAssisComp/data-validator.git

environment:
  sdk: ^3.2.3

dependencies:

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
