name: Dart

on:
  push:
    branches: "*"
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Data Validator Package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Note: This workflow uses the latest stable version of the Dart SDK.
      # You can specify other versions if desired, see documentation here:
      # https://github.com/dart-lang/setup-dart/blob/main/README.md
      # - uses: dart-lang/setup-dart@v1
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Install dependencies
        run: dart pub get

      - name: Verify formatting
        run: dart format --set-exit-if-changed lib test

      - name: Analyze project source
        run: dart analyze --fatal-infos --fatal-warnings lib test

      - name: Generate docs 
        run: dart docs

      - name: Runing unit tests
        run: |
          dart pub global activate coverage
          dart pub global run coverage:test_with_coverage

      - name: Making sure that code coverage is 100
        uses: VeryGoodOpenSource/very_good_coverage@v2
        with:
          min_coverage: 100

          
